### ISSUE TITLE
GitHub Project and Kanban Setup Review

### ISSUE THREAD

**Issue by peter-akhigbe** [bronnie313/ruby-capstone-project#34]
Hello Reviewer,

We're excited to share our progress on the Ruby Capstone Project. We've set up our GitHub project and Kanban board to manage tasks and streamline our workflow. As this is our first time using a GitHub project and Kanban board, we kindly request your assistance in double-checking our setup to ensure that we're on the right track.

**GitHub Project Link:** [Link to GitHub Project](https://github.com/bronnie313/ruby-capstone-project/projects/1)

**Number of People in the Team:** 3

**Team Members:**
- Team member 1: @wilhelmk109
- Team member 2: @bronnie313
- Team member 3: @peter-akhigbe

Your feedback is crucial in helping us optimize our project management process. Please feel free to review our GitHub project and Kanban board and provide any suggestions or recommendations in the comments below. We greatly appreciate your time and insights.

Thank you!

Best regards,
Peter Akhigbe (Task Assigner)

**Comment by danmainah** [comment]
Hi @peter-akhigbe , @bronnie313 and @WilhelmK109 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Added the required info correctly in the review issue
✔️  Used the design given in the kanban board and assigned all tasks fairly to every team member

# Required Changes ♻️

- [ ] @Team great work on your Kanban board however there are two tasks that have the wrong title, one for listing the options and another for creating the schema files for team member 3 , kindly consider rectifying the mistake
![image](https://github.com/bronnie313/ruby-capstone-project/assets/61408860/2cd055dc-fe74-4789-8ee0-4b6bb69f8abc)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by peter-akhigbe** [comment]
Hello @danmainah,

Thanks for the review, the error has been corrected.

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

<img src="https://media4.giphy.com/media/sR9nilEznDoSlga667/giphy.gif"/> 

## Highlights
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
